Metrics/AbcSize:
  Max: 30 # TODO: lower

Metrics/CyclomaticComplexity:
  Max: 10 # TODO: lower

Metrics/BlockLength:
  Max: 40 # TODO: lower
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Style/FileName:
  Enabled: false
