Metrics/CyclomaticComplexity:
  Max: 10 # TODO: lower

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/PerceivedComplexity:
  Max: 10

Style/FileName:
  Enabled: false

Documentation:
  Enabled: false

# TODO: Fix the TODOs
inherit_from: .rubocop_todo.yml
