common_word_team_names: ['real', 'nice', 'city']

blacklisted_adjectives:
- spanish
- german
- english
- french
- italian
- russian
- chinese
- american
- austrian
- canadian
- turkish
- bulgarian
- brazilian
- colombian
- one
- two
- three
- four
- five
- six
- seven
- eight
- nine
- ten
- costa
- finishing
- cr7
- west
- foul

blacklisted_adjective_patterns:
- ^[0-9]+(th|st|nd|rd)$
- ^(?!.*[a-zA-Z]).*$

max_adjectives_per_team: 3

common_adjectives_to_exclude: 100

min_count: 5

scoring:
  local_frequency_coefficient: 1
  global_frequency_coefficient: -1

sequence:
  phase2:
    - filter-blacklisted-adjectives
    - filter-common-adjectives
    - score
    - sort-teams
    - filter-low-count-adjectives
    - take-top
