blacklisted_adjectives:
# Nationalities
- spanish
- german
- english
- french
- italian
- russian
- chinese
- american
- austrian
- canadian
- turkish
- bulgarian
- brazilian
- colombian
- irish
- jewish
- danish
- polish
- mexican
- argentinian
- dutch
- belgian
# Numbers
- one
- two
- three
- four
- five
- six
- seven
- eight
- nine
- ten
# Colors
- blue
- yellow
- white

# Non-adjectives
- costa
- finishing
- cr7
- foul
- live
- key
- saint-etienne
# Other
- west # Usually West Ham or West Bromwich
- east
- top
- mid
- low

blacklisted_adjective_patterns:
- ^[0-9]+(th|st|nd|rd)$ # 1st, 5th, etc.
- ^(?!.*[a-zA-Z]).*$ # No letters
- ^[0-9]+(m|mil)$ # Prices: 80m, 100mil, etc.

max_adjectives_per_team: 3

common_adjectives_to_exclude: 100

min_count: 5

scoring:
  local_frequency_coefficient: 1
  global_frequency_coefficient: -1

sequence:
  phase2:
    - filter-blacklisted-adjectives
    - filter-common-adjectives
    - score
    - sort-teams
    - filter-low-count-adjectives
    - take-top
