# EPL
- canonical_name: Arsenal
  alternative_names: ['Gunners']
- canonical_name: Manchester United
  alternative_names: ['Red Devils', 'MU']
- canonical_name: Chelsea
  alternative_names: ['Pensioners', 'CFC']
- canonical_name: Liverpool
  alternative_names: ['LFC']
- canonical_name: Manchester City
  alternative_names: ['The Citizens', 'The Sky Blues', 'Man City', 'ManCity']
- canonical_name: Tottenham
  alternative_names: ['Spurs', 'Lilywhites']
- canonical_name: Leicester
  alternative_names: ['The Foxes']
- canonical_name: Everton
  alternative_names: ['Toffees']
- canonical_name: West Ham
  alternative_names: ['The Irons', 'The Hammers', 'Westham']
- canonical_name: Swansea
  alternative_names: ['The Swans']
- canonical_name: Crystal Palace
  alternative_names: ['The Eagles', 'The Glaziers']
- canonical_name: West Bromwich
  alternative_names: ['The Baggies', 'The Throstles']
- canonical_name: Southampton
  alternative_names: ['The Saints']
- canonical_name: Stoke City
  alternative_names: ['The Potters']
- canonical_name: Watford
  alternative_names: ['The Hornets', 'The Golden Boys', 'Yellow Army', "The 'Orns'"]
- canonical_name: Newcastle United
  alternative_names: ['Newcastle', 'The Magpies', 'Geordies', 'Toon']
- canonical_name: Burnley
  alternative_names: ['BFC', 'The Clarets']
- canonical_name: Brighton & Hove Albion
  alternative_names: ['The Seagulls', 'Brighton']
- canonical_name: Huddersfield Town
  alternative_names: ['Huddersfield', 'The Terriers']
- canonical_name: Bournemouth
  alternative_names: ['Boscombe']

# Spain
- canonical_name: Barcelona
  alternative_names: ['Barca']
- canonical_name: Alavés
  alternative_names: ['Alaves']
- canonical_name: Athletic Bilbao
  alternative_names: ['Athletic', 'Bilbao']
- canonical_name: Atletico Madrid
  alternative_names: ['Atlético', 'Atletico']
- canonical_name: Celta Vigo
  alternative_names: ['Celta']
- canonical_name: Deportivo
  alternative_names: []
- canonical_name: Eibar
  alternative_names: []
- canonical_name: Espanyol
  alternative_names: []
- canonical_name: Granada
  alternative_names: []
- canonical_name: Las Palmas
  alternative_names: []
- canonical_name: Leganés
  alternative_names: ['Leganes']
- canonical_name: Málaga
  alternative_names: ['Malaga']
- canonical_name: Osasuna
  alternative_names: ['Osasuna']
- canonical_name: 'Real Betis'
  alternative_names: ['Betis']
- canonical_name: Real Madrid
  alternative_names: ['Real', 'RM']
- canonical_name: Real Sociedad
  alternative_names: []
- canonical_name: Sevilla
  alternative_names: []
- canonical_name: Sporting Gijón
  alternative_names: ['Gijón', 'Gijon']
- canonical_name: Valencia
  alternative_names: []
- canonical_name: Villarreal
  alternative_names: []

# Germany
- canonical_name: Bayern Munich
  alternative_names: ['Munich', 'Bayern']
- canonical_name: Borussia Dortmund
  alternative_names: ['Borussia', 'Dortmund', 'BVB']
- canonical_name: Hamburger SV
  alternative_names: ['Hamburger']
- canonical_name: Werder Bremen
  alternative_names: ['Werder']
- canonical_name: Schalke 04
  alternative_names: ['Schalke']
- canonical_name: Eintracht Frankfurt
  alternative_names: ['Eintracht']
- canonical_name: FC Köln
  alternative_names: ['Köln', 'Koln']
- canonical_name: Hertha BSC
  alternative_names: ['Hertha']
- canonical_name: Borussia Mönchengladbach
  alternative_names: ['Mönchengladbach', 'Monchengladbach']
- canonical_name: Bayer 04 Leverkusen
  alternative_names: ['Leverkusen']
- canonical_name: VfL Wolfsburg
  alternative_names: ['Wolfsburg']
- canonical_name: FSV Mainz 05
  alternative_names: [' Mainz']
- canonical_name: TSG 1899 Hoffenheim
  alternative_names: ['Hoffenheim']
- canonical_name: FC Augsburg
  alternative_names: ['Augsburg']
- canonical_name: SC Freiburg
  alternative_names: ['Freiburg']
- canonical_name: RB Leipzig
  alternative_names: ['Leipzig']
- canonical_name: VfB Stuttgart
  alternative_names: ['Stuttgart']
- canonical_name: Hannover 96
  alternative_names: ['Hannover']

# Italy
- canonical_name: Juventus
  alternative_names: ['JFC', 'Juve']
- canonical_name: Inter
  alternative_names: ['Internazionale']
- canonical_name: Atalanta
  alternative_names: []
- canonical_name: Benevento
  alternative_names: []
- canonical_name: Bologna
  alternative_names: []
- canonical_name: Cagliari
  alternative_names: []
- canonical_name: Chievo
  alternative_names: []
- canonical_name: Crotone
  alternative_names: []
- canonical_name: Fiorentina
  alternative_names: []
- canonical_name: Genoa
  alternative_names: []
- canonical_name: Hellas Verona
  alternative_names: ['Hellas']
- canonical_name: Lazio
  alternative_names: []
- canonical_name: Milan
  alternative_names: []
- canonical_name: Napoli
  alternative_names: []
- canonical_name: Roma
  alternative_names: []
- canonical_name: Sampdoria
  alternative_names: []
- canonical_name: Sassuolo
  alternative_names: []
- canonical_name: SPAL
  alternative_names: []
- canonical_name: Torino
  alternative_names: []
- canonical_name: Udinese
  alternative_names: []

# France
- canonical_name: PSG
  alternative_names: ['Paris Saint-Germain', 'Paris Saint Germain', 'Paris SG']
- canonical_name: Monaco
  alternative_names: ['ASM']
- canonical_name: Angers
  alternative_names: []
- canonical_name: Bastia
  alternative_names: []
- canonical_name: Bordeaux
  alternative_names: []
- canonical_name: Caen
  alternative_names: []
- canonical_name: Dijon
  alternative_names: []
- canonical_name: Guingamp
  alternative_names: []
- canonical_name: Lille
  alternative_names: []
- canonical_name: Lorient
  alternative_names: []
- canonical_name: Olympique Lyonnais
  alternative_names: ['Olympique', 'Lyon']
- canonical_name: Marseille
  alternative_names: []
- canonical_name: Metz
  alternative_names: []
- canonical_name: Montpellier
  alternative_names: []
- canonical_name: Nancy
  alternative_names: []
- canonical_name: Nantes
  alternative_names: []
- canonical_name: Nice
  alternative_names: []
- canonical_name: Rennes
  alternative_names: []
- canonical_name: Rennes
  alternative_names: []
- canonical_name: Saint-Étienne
  alternative_names: ['Saint Étienne', 'Saint-Etienne', 'Saint Etienne']
- canonical_name: Toulouse
  alternative_names: []

# Portugal
- canonical_name: Benfica
  alternative_names: []
- canonical_name: Porto
  alternative_names: []
- canonical_name: Arouca
  alternative_names: []
- canonical_name: Belenenses
  alternative_names: []
- canonical_name: Boavista
  alternative_names: []
- canonical_name: Braga
  alternative_names: []
- canonical_name: Chaves
  alternative_names: []
- canonical_name: Estoril
  alternative_names: []
- canonical_name: Feirense
  alternative_names: []
- canonical_name: Marítimo
  alternative_names: ['Maritimo']
- canonical_name: Moreirense
  alternative_names: []
- canonical_name: Nacional
  alternative_names: []
- canonical_name: Paços de Ferreira
  alternative_names: ['Pacos de Ferreira']
- canonical_name: Rio Ave
  alternative_names: []
- canonical_name: Sporting CP
  alternative_names: ['Sporting']
- canonical_name: Tondela
  alternative_names: []
- canonical_name: Vitória de Guimarães
  alternative_names: [Vitoria de Guimaraes]
- canonical_name: Vitória de Setúbal
  alternative_names: ['Vitoria de Setubal']

# Russia
- canonical_name: Zenit
  alternative_names: []
- canonical_name: CSKA
  alternative_names: []
- canonical_name: Spartak
  alternative_names: []

# MLS
- canonical_name: Sounders
  alternative_names: ['Seattle']
- canonical_name: Timber
  alternative_names: ['Portland']
