# EPL
- canonical_name: Arsenal
  alternative_names: ['Gunners']
- canonical_name: Manchester United
  alternative_names: ['Red Devils', 'MU']
- canonical_name: Chelsea
  alternative_names: ['Pensioners', 'CFC']
- canonical_name: Liverpool
  alternative_names: ['LFC']
- canonical_name: Manchester City
  alternative_names: ['The Citizens', 'The Sky Blues', 'Man City', 'ManCity']
- canonical_name: Tottenham
  alternative_names: ['Spurs', 'Lilywhites']
- canonical_name: Leicester
  alternative_names: ['The Foxes']
- canonical_name: Everton
  alternative_names: ['Toffees']
- canonical_name: West Ham
  alternative_names: ['The Irons', 'The Hammers', 'Westham']
- canonical_name: Swansea
  alternative_names: ['The Swans']
- canonical_name: Crystal Palace
  alternative_names: ['The Eagles', 'The Glaziers']
- canonical_name: West Bromwich
  alternative_names: ['The Baggies', 'The Throstles']
- canonical_name: Southampton
  alternative_names: ['The Saints']
- canonical_name: Stoke City
  alternative_names: ['The Potters']
- canonical_name: Watford
  alternative_names: ['The Hornets', 'The Golden Boys', 'Yellow Army', "The 'Orns'"]
- canonical_name: Newcastle United
  alternative_names: ['Newcastle', 'The Magpies', 'Geordies', 'Toon']
- canonical_name: Burnley
  alternative_names: ['BFC', 'The Clarets']
- canonical_name: Brighton & Hove Albion
  alternative_names: ['The Seagulls', 'Brighton']
- canonical_name: Huddersfield Town
  alternative_names: ['Huddersfield', 'The Terriers']
- canonical_name: Bournemouth
  alternative_names: ['Boscombe']

# Spain
- canonical_name: Barcelona
  alternative_names: ['Barca']

# Germany
- canonical_name: Bayern
  alternative_names: ['Munich']
- canonical_name: Borussia Dortmund
  alternative_names: ['Borussia', 'Dortmund', 'BVB']

# Italy
- canonical_name: Juventus
  alternative_names: ['JFC', 'Juve']
- canonical_name: Inter
  alternative_names: ['Internazionale']

# France
- canonical_name: PSG
  alternative_names: ['Paris Saint-Germain', 'Paris SG']
- canonical_name: Monaco
  alternative_names: ['ASM']

# Portugal
- canonical_name: Benfica
  alternative_names: []
- canonical_name: Porto
  alternative_names: []

# Russia
- canonical_name: Zenit
  alternative_names: []
- canonical_name: CSKA
  alternative_names: []
- canonical_name: Spartak
  alternative_names: []

# MLS
- canonical_name: Sounders
  alternative_names: ['Seattle']
- canonical_name: Timber
  alternative_names: ['Portland']
